id: DC537B88A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:21:40+00:00'
last_modified: '2022-05-26T11:01:35.252421+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '8971':
      image_group_id: I1PD95871
      title: ཕྱག་རྒྱ་བཞི་གཏན་ལ་དབབ་པ།
      total_pages: 1902
      order: 26
      base_file: 8971.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
