id: 62beec591c684cf3beec46640ea73017
initial_creation_type: ocr
source_metadata:
  volumes:
    065d1aa554b4428c8f8f36e2cb4d4a34:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ཕྱག་རྒྱ་བཞི་གཏན་ལ་དབབ་པ།
      total_pages: 1902
      volume_number: 26
