id: 62beec591c684cf3beec46640ea73017
initial_creation_type: ocr
source_metadata:
  volumes:
    1d2cff6869ee459fb4fcd49a5af4fe66:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ཕྱག་རྒྱ་བཞི་གཏན་ལ་དབབ་པ།
      total_pages: 1902
      volume_number: 26
